### PR TITLE
feat: contact form

### PR DESCRIPTION
**Pull request by pfulton**
This adds markup and styling for the contact form and for the list of contacts on the Contact Us template.

### CODE REVIEW

**Comment by pfulton** [comment]
localhost_8000_cmesh_contact_

**Comment by pfulton** [comment]
@hachacha @mdlincoln A few questions for this template:

* The mockup has a different style for the page title (Contact Us), but that style is different than it is elsewhere. I kept the consistent style, but I can change it to match the mockup. What do you think?
* The contact form template tags that were already in here are passing a `foundation` arg for each field tag. I tried hunting around to see if/where I could modify the markup for those tags, but I couldn't track it down. If you're ok with how this looks, then we'll leave it. Otherwise, please let me know how I can modify the HTML that rides along with those tags - or if I'd need to just do regular form `<label>` and `<input />` HTML - I just don't know how to make sure that I'm hooking things up correctly for the Python side of things.
* The list of representatives below the form - what information should we show for each representative? The mockup shows slightly different info than what's getting displayed here.

**Comment by hachacha** [comment]
1. I think it's better to be consistent.
2. Just did a test and it seems that the foundation filter doesn't really do anything from what I can tell. I'm okay with how this looks but I would just remove the `| foundation` portions. On this page the contact form is being loaded as an object and the values turn into fields. 
3. Not sure what to put here, but there's been discussion on how to break up the publishing portion from the cmesh/ethos portion so I'll make an issue in the dev board to find out.
Thank you.

**Comment by hachacha** [comment]
1. I think it's better to be consistent.
2. So it looks like foundation is pulling the labels from the `verbose_name` field that is on the Contact model, but when looking for the particular contact to render it's not referencing a specific journal-- I imagine this must be a TODO for Birkbeck...
So, for us for now to get closer to the mockup I would use <label> and <input>
```
name="sender" required id="id_sender"
name="subject" required id="id_subject"
name="body" required id="id_body"
{{ contact_form.are_you_a_robot|foundation }}
```
leave the areyouarobot portion as is

We DO need a default recipient of these emails to be sent with the message and I think it's just going to be one person so just throw this in the form:  
`<input type="hidden" name="recipient" id="id_recipient" value="{{contacts.0.email}}" />` 

3. Not sure what to put here, but there's been discussion on how to break up the publishing portion from the cmesh/ethos portion so I'll make an issue in the dev board to find out.
Thank you.

**Comment by hachacha** [comment]
added just the hidden element. the sender, subject and body still need to be there, not sure how those should be styled up.
https://github.com/dSHARP-CMU/cmesh-dev/issues/217

**Comment by pfulton** [comment]
One final question/note here:
The mockup gives the appearance of `<input>` elements without traditionally displayed `<label>` elements. It looks like the suggestion is to use the `<input>` element's `placeholder` attribute. While the placeholder element _does_ give a hint as to what content belongs in the `<input>`, there's an accessibility issue: assistive tech (screen readers) do not announce the `placeholder` attribute - and there's a UX issue in that the `placeholder` disappears when an `<input>` gains focus or is tapped on.

I'm happy to stay true to the mockup - or we could leave the form the way it is currently. See below, @mdlincoln @hachacha 

---

## Current implementation

Screen Shot 2019-03-11 at 8 58 10 PM

## Mockup
Screen Shot 2019-03-11 at 8 58 33 PM

**Comment by hachacha** [comment]
Your suggestions regarding not using placeholder makes sense. I think that accessibility is more important than this particular design feature. If someone really is concerned about this then we can change to placeholders.

**Pull request merged**
